### ISSUE TITLE
Naphthazarin research manuscript

### ISSUE THREAD

**Issue by bebi78** [OpenSourceMycetoma/Adjuvant-Screen#3]
Research manuscript about the activity of naphthazarin against M. mycetomatis.

**Comment by bebi78** [comment]
@MA-Jjingyi @wwjvdsande @mattodd Please find attached a first manuscript draft about the naphthazarin results. It is written in Wiley style using the template of the journal Chem. Biodiversity (IF 2.8), which seems to me an accurate journal in its current form. 
Please add and correct as you like. Some remarks in red-yellow might be answered by @MA-Jjingyi. Suggestions for a graphical abstract (still missing in the manuscript) are also welcome.

[bb.naphthazarin.mycetoma.ChemBiodiv.Template.docx](https://github.com/OpenSourceMycetoma/Adjuvant-Screen/files/10351372/bb.naphthazarin.mycetoma.ChemBiodiv.Template.docx)

**Comment by MA-Jjingyi** [comment]
@bebi78 Happy New Year. thanks for your first manuscript draft about the naphthazarin results. we are working on this manuscript. we will check all data of this paper and leave our comments as soon as possible.

**Comment by bebi78** [comment]
@MA-Jjingyi Thanks. Wish you also a Happy New Year! I took the part of the Galleria mellonella activity for the experimental section from Wilson's paper about the pandemic response box (i.e., drug administration after 4 h, 28 h and 52 h).  I was not sure if you used the same procedure. If you used a different naphthazarin administration scheme please correct.

**Comment by bebi78** [comment]
@MA-Jjingyi @wwjvdsande @mattodd Please find attached the most recent version of the naphthazarin manuscript and a powerpoint file with the graphical abstract. Please check again and correct if you find any mistakes, or if you want to modify the graphical abstract.

[bb.naphthazarin.mycetoma.ChemBiodiv.Template.200123.docx](https://github.com/OpenSourceMycetoma/Adjuvant-Screen/files/10466967/bb.naphthazarin.mycetoma.ChemBiodiv.Template.200123.docx)

[GraphicalAbstract.napththazarin.pptx](https://github.com/OpenSourceMycetoma/Adjuvant-Screen/files/10466969/GraphicalAbstract.napththazarin.pptx)

**Comment by wwjvdsande** [comment]
@bebi78 the graphical abstract looks great. 
[bb.naphthazarin.mycetoma.ChemBiodiv.Template.200123.docx](https://github.com/OpenSourceMycetoma/Adjuvant-Screen/files/10467362/bb.naphthazarin.mycetoma.ChemBiodiv.Template.200123.docx)

**Comment by bebi78** [comment]
@mattodd Would need your OK for the manuscript. Then I can submit it asap.

**Comment by bebi78** [comment]
@mattodd Most recent naphthazarin manuscript draft attached.
[bb.naphthazarin.mycetoma.ChemBiodiv.Template.docx](https://github.com/OpenSourceMycetoma/Adjuvant-Screen/files/10489937/bb.naphthazarin.mycetoma.ChemBiodiv.Template.docx)

**Comment by mattodd** [comment]
> @mattodd Most recent naphthazarin manuscript draft attached. [bb.naphthazarin.mycetoma.ChemBiodiv.Template.docx](https://github.com/OpenSourceMycetoma/Adjuvant-Screen/files/10489937/bb.naphthazarin.mycetoma.ChemBiodiv.Template.docx)

Will look ASAP.

**Comment by bebi78** [comment]
@mattodd Already had a look?

**Comment by bebi78** [comment]
@MFernflower Is it OK for you if we add your name to the authors list of the manuscript? Would need your address or affiliation then.

**Comment by MFernflower** [comment]
I did not really do anything with regards to the quinones series @bebi78

**Comment by bebi78** [comment]
@MFernflower OK, but we want to mention you in the Acknowledgments at least. 
I count on you for the future perfumes paper then.

**Comment by MFernflower** [comment]
Yes indeed that is correct

@mattodd has my information so he could add to manuscript

**Comment by bebi78** [comment]
@mattodd Just sent the revised version of the manuscript.

**Comment by bebi78** [comment]
@OpenSourceMycetoma/corecontrib @MFernflower The naphthazarin manuscript was accepted today, see link :-) 
Should be soon open access (already applied for it).

https://onlinelibrary.wiley.com/doi/abs/10.1002/cbdv.202300151

**Comment by bebi78** [comment]
@mattodd @wwjvdsande @MA-Jjingyi Open access was approved. Waiting for the proofs now and will let you know then.

**Comment by MFernflower** [comment]
PAPER IS LIVE SEE https://onlinelibrary.wiley.com/doi/full/10.1002/cbdv.202300151
